version: '3.8'

services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./spark-cluster/data:/opt/spark-data
